[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
block_timestamp = 1692693343
[profile.test]
src = 'test/foundry'
[fuzz]
runs = 5000